# Generated by Django 2.2.7 on 2020-02-18 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_head_image', models.ImageField(upload_to='')),
                ('nickname', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('user_level', models.IntegerField(default=0)),
                ('user_state', models.BooleanField(default=False)),
                ('is_super_user', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserJokes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joke_states', models.IntegerField(choices=[(0, '未审核'), (1, '状态正常'), (2, '自行删除'), (3, '未通过审核'), (4, '举报次数过多'), (5, '包含敏感词汇')], default=0)),
                ('joke_content', models.TextField()),
                ('joke_image', models.ImageField(null=True, upload_to='')),
                ('joke_video', models.FileField(null=True, upload_to='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnneJokes.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=8)),
                ('user_gender', models.IntegerField(choices=[(0, '未填写'), (1, '男'), (2, '女'), (3, '不方便透露')], default=0)),
                ('user_birthday', models.DateTimeField()),
                ('user_autograph', models.CharField(default='', max_length=64)),
                ('user_country', models.CharField(max_length=12)),
                ('user_address', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnneJokes.User')),
            ],
        ),
    ]
