# Generated by Django 2.2.7 on 2020-02-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnneJokes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjokes',
            name='joke_image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userjokes',
            name='joke_video',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
