# Generated by Django 2.2.7 on 2020-02-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnneJokes', '0003_jokecomment_jokeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jokecomment',
            name='comment_state',
            field=models.BooleanField(default=True),
        ),
    ]
